### ISSUE TITLE
Add multiple image upload

### ISSUE THREAD

**Issue by minils** [vasiljevski/admirorgallery#26]
It would be very nice if one could upload multiple images at once.

**Comment by vasiljevski** [comment]
Hi, 
We already have that option. But it is a bit tricky.
You just need to zip all the images and upload the zip file.
Image Manager will unpack them and you will have all images uploaded at once.

**Comment by vasiljevski** [comment]
Is that something you could use, or do you have some suggestion that would be more user friendly?
Any suggestion would be appreciated, thanks.

**Comment by minils** [comment]
Maybe it would be good to add an info box or something like this so that people know that they can upload zipped albums.
